#ifndef CONFIGURATION_H
#define CONFIGURATION_H

// CONTANTES
#define WIFI_SSID "Aquapony"
#define WIFI_PASSWORD "12345678"
#define LOCAL_WIFI_SSID "SUELI"
#define LOCAL_WIFI_PASSWORD "santos1965"
#define WIFI_MAX_CONNECTIONS 1
#define WIFI_DEFAULT_IP "192.168.0.4"
#define WIFI_CHANNEL 1
#define SERVER_PORT 80
#define SOCKET_URL "/ws"
#define EVENTS_URL "/events"

#define MIN_AQUARIUM_TEMP 23
#define MAX_AQUARIUM_TEMP 28
#define MIN_AQUARIUM_PH 6
#define MAX_AQUARIUM_PH 7
#define PPM_ML_L 10

#define EEPROM_SIZE 4096


#define PIN_BUTTON_RESET 19


// INPUTS
#define PIN_THERMOCOUPLE 14             // PINO: SENSOR DE TEMPERATURA 
#define PIN_PH 35                       // PINO: SENSOR DE PH
#define PIN_TURBIDITY 34                // PINO: SENSOR DE TURBIDADE

#define PIN_CLOCK_CLK 4
#define PIN_CLOCK_DAT 2
#define PIN_CLOCK_RST 15

// OUTPUTS
#define PIN_HEATER 5                   // PINO: AQUECEDOR
#define PIN_WATER_PUMP 18               // PINO: BOMBA DE AGUA
#define PIN_COOLING 13                  // NÃO IMPLEMENTADO



// ENDERÇOS DE MEMORIA EEMPROM
#define ADDRESS_SSID 0x0001
#define ADDRESS_PASSWORD 0x0002

#define ADDRESS_AQUARIUM_TEMPERATURE 0x0003
#define ADDRESS_AQUARIUM_MIN_TEMPERATURE 0x0007
#define ADDRESS_AQUARIUM_MAX_TEMPERATURE 0x00B
#define ADDRESS_AQUARIUM_MAX_PH 0x00B
#define ADDRESS_AQUARIUM_MIN_PH 0x00B
#define ADDRESS_DOSAGEM_REDUTOR_PH 0x00B
#define ADDRESS_PPM_PH 0x00B

// #define ADDRESS_CYCLE_TIME_WATER_PUMP 0x0006
// #define ADDRESS_NUMBER_CYCLE_TIME_WATER_PUMP 0x0007



#endif